# Generated by Django 5.2.14 on 2026-05-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='adress',
        ),
    ]
