# Generated by Django 5.2.14 on 2026-05-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_rename_link_link_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='adress',
            new_name='address',
        ),
    ]
