# Generated by Django 5.2.14 on 2026-05-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_rename_adress_link_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
